name: Nop bai HTML buoi 6

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: ðŸš€ Deploy bÃ i buá»•i 6 lÃªn Somee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mÃ£ nguá»“n
        uses: actions/checkout@v3

      - name: Deploy qua FTP Ä‘áº¿n Somee
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 155.254.246.42
          username: TMyChomTran
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www.oss106.somee.com/
